DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS images;

CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS images(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    file BLOB NOT NULL,
    mimetype TEXT NOT NULL,
    name TEXT NOT NULL,
    size INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(id)
);